# This is a basic workflow to help you get started with Actions

name: Generate Github releases

# Controls when the action will run. 
on:
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  generate-github-release:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
                    
      - name: Install xmlstarlet
        run: sudo apt install xmlstarlet
        
      - name: find last description
        id: last-description
        run: |
          SEMVERSION=$(echo "${{ github.ref_name }}" | sed 's/v//')
          echo ::set-output name=description-output::$(\
          xmlstarlet select --template --var semvers="'$SEMVERSION'" --value-of '/component/releases/release[@version=$semvers]/description/ul/li' --nl ./eu.skribisto.skribisto.appdata.xml \
          )
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |           
            ${{ steps.last-description.outputs.description-output }}
            
            Automated Release by GitHub Action CI
          draft: false
          prerelease: false
