# This is a basic workflow to help you get started with Actions

name: Generate Windows package

# Controls when the action will run. 
on:
  workflow_run:
    workflows: [Generate Github releases]
    types: [completed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  generate-github-release:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
          


          
          
          
      - name: Gets latest created release info
        id: latest_release_info
        uses: jossef/action-latest-release-info@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Upload asset to github release page
        id: upload-release-asset
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.latest_release_info.outputs.upload_url }}
          asset_path: ./dist/output.tar
          asset_name: output_${{ steps.latest_release_info.outputs.tag_name }}.tar
          asset_content_type: application/x-tar
