# This is a basic workflow to help you get started with Actions

name: Generate releases in .appdata.xml from NEWS.yml

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  generate-release-in-appdata:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: 'develop'

      - id: git-diff
        run: echo "::set-output name=diff-output::$(git diff origin/master...origin/develop -- NEWS.yml)"

      - name: Run a multi-line script
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          appstreamcli news-to-metainfo --limit=6 ./NEWS.yml ./eu.skribisto.skribisto.appdata.xml
          git add .
          git commit -m "releases in AppData generated"
          git push
        if: steps.git-diff.outputs.diff-output != ''
          
